spring.application.name=geolocation

spring.datasource.url=jdbc:postgresql://localhost:5432/geolocation
spring.datasource.username=postgres
spring.datasource.password=1212

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect