spring.application.name=ryde

spring.datasource.url=jdbc:postgresql://localhost:5432/geolocation
spring.datasource.username=postgres
spring.datasource.password=1212

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=http://localhost:5173